services:
  app:
    image: todo-frontend-dev # Already built image!
    volumes:
      - ./todo-frontend:/usr/src/app
    container_name: todo-frontend-dev-served
  server:
    image: todo-backend-dev
    volumes:
      - ./todo-backend:/usr/src/app
    container_name: todo-backend-dev-served
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: todo-reverse-proxy
    depends_on:
      - app # wait for the frontend container to be started
