services:
  app:
    image: blog-frontend
    build:
      context: ./blog-frontend
      dockerfile: Dockerfile
  server:
    image: blog-backend
    build:
      context: ./blog-backend
      dockerfile: Dockerfile
    env_file:
      - ./blog-backend/.env
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - app
      - server
